---

- name: "[Pretask] Update apt cache"
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 36000

- name: '[Pretask] Install pip'
  hosts: all
  tasks:
    - name: Install required packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-pip
    - name: Install required pip packages
      pip:
        name: pymongo
        state: present

- name: '[Pretask] Install docker'
  hosts: all
  roles:
    - role: docker

- name: '[Pretask] Create directories'
  hosts: all
  vars:
    docker_service_directory_db: /data/dummy/db
  tasks:
    - name: Create db data directory
      file:
        path: "{{ docker_service_directory_db }}"
        state: directory
        owner: "{{ uid | default(ansible_env['SUDO_USER']) }}"
        group: "{{ gid | default(ansible_env['SUDO_USER']) }}"
        mode: 0700

- name: Deploy the docker image managed by a systemd service
  hosts: all
  vars:
    docker_image: nginx:alpine
    db_type: mongo
    docker_db_image: mongo
    service_name: dummy
    docker_service_directory_db: /data/dummy/db
    docker_command: |
      /usr/bin/docker run --rm --name {{ service_name }} \
      -p 8080:80 \
      -v {{ docker_service_volume_name }}:/usr/share/nginx/html \
      --network {{ service_name }} \
      {{ docker_image }}
    db_user_pass: 's3cr3t'
    db_config_port: 27017
    db_name: dummy
    db_user: johndoe
  roles:
    - role: generic_docker_systemd
