---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster
    box: debian/buster64
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: 172.16.100.12
        type: static
    config_options:
      vbguest.auto_update: false
    instance_raw_config_args:
      - "vm.synced_folder '.', '/vagrant', disabled: true"
    groups:
      - anarres
lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint --exclude molecule/ --exclude library/ --exclude .github/
  flake8 --exclude roles,molecule,library
provisioner:
  name: ansible
  options:
    become: true
    extra-vars: "{'testing': true, domain: 'anarres.local'}"
verifier:
  name: testinfra
  options:
    sudo: true
